### ISSUE TITLE
Comment here to be added as a collaborator

### ISSUE THREAD

**Issue by brianamarie** [githubschool/sep-3#1]
### Comment below - you can say anything 
 We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API and some fancy chatops. Once you comment, we will add you as a collaborator. 

  You'll also start to receive a lot of emails. (:exclamation:) You can slow these down immediately by clicking the 'unsubscribe' button.

**Comment by prijssen** [comment]
test

**Comment by jspaans91** [comment]
Test

**Comment by MaisQbs** [comment]
Test 3

**Comment by Gjaltz** [comment]
Gjalt is online

**Comment by janvandenvelden** [comment]
Hello

**Comment by cndekoning** [comment]
goedemorgen

**Comment by ECGBM** [comment]
goedemorgen

**Comment by andrebzk** [comment]
goedemorgen

**Comment by CornGr** [comment]
Duurt ff, maar dan heb je ook wat
